### ISSUE TITLE
Ryuuki Network Website - write mission driven blurb

### ISSUE THREAD

**Issue by DanM3rcurius** [Cardano-Community-Builders/Ryuuki#16]
## What is a Mission Driven Stakepool
A Mission Driven stake pool is connected to a project or team that itself is mission driven. The Stakepool has soul, so to speak.

### Well what exactly is mission driven? 
We refer to something as mission driven, if the focus of the project is on a clearly defined purpose. Usually that purpose involves open source (or commons) contributions, creation of closed loops systems, ecological sustainability or regeneration and regenerative practices.

## Some Alchemy.
What happens if you mix two things together? You receive a third new thing. Hence combining the mission driven aspect with stake pool operation leaves us with a novel kind of entity, that is able to self sufficiently and organically grow & nurture community around a cause. 
We can go on further and mix this entity with again something new, like DripDropz and voila never before seen or felt possibilities emerge!

Take a ride with us.

**Comment by DanM3rcurius** [comment]
@stephen-rowan please have a look 🙏🏿

**Comment by stephen-rowan** [comment]
Will do - thanks Dan

**Comment by stephen-rowan** [comment]
Hi @DanM3rcurius  - I can put this in Ryuuki's documentation section (currently titled "Delegate") like this https://cardano-community-builders.github.io/docs/ or incorporate it into one of the about pages like this https://cardano-community-builders.github.io/about/ . The fonts, colours and graphics can all be tweaked - just organising the content for now.

**Comment by DanM3rcurius** [comment]
Dear Stephen, my feeling is it would be better suited in the about section.
Where do you upload the content to in order for it to be built with pages?
I tried looking around but couldn't find anything.
What do the others think

Cheers
D

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by stephen-rowan** [comment]
OK Dan, the content for _About_ is included here https://github.com/Cardano-Community-Builders/cardano-community-builders.github.io/tree/main/content/en/about. 

But this is a Hugo template so you have know what the short codes do otherwise it will break easily. I can take you through how it works if you like. Here is a guide https://www.docsy.dev/docs/adding-content/content/

Basically once you update Hugo templates this triggers 1) an action to check it works and 2) another to update the release (on the website branch). 

The whole look and feel can be tweaked by modifying shortcodes in the /layouts, adding graphics in /assets (see https://www.docsy.dev/docs/adding-content/lookandfeel/).

S

**Comment by DanM3rcurius** [comment]
Thanks for the links Stephen! Went over the docs on how to add content, reads quite straightforward. If you haven't added the content yet I will try it out today, so you have 1 less task on the table.🙏

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by DanM3rcurius** [comment]
uploaded. need to fix some layout, but content done
